title: MVKUltra's Cave of Wonders
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A crack appears in the rock, you squeeze through and enter a Cave of Wonders!
  Everywhere you look are assorted treasures and trinkets of incredible beauty. 
  A sign hovers in the air about you, it says "Welcome stranger, to MVKUltra's 
  Cave of Wonders"! Scroll down to look around...
# social links
twitter_username: @MVKUltra
github_username:  MVKUltra

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
